# =============================================================================
# Build Arena-Level Movement Model Dataset
# Project: Effects of parasitic infection on predation risk responses in
#          blue mussels (Mytilus edulis)
# Description:
#   This script merges individual-level movement and infection data into an
#   arena-level summary dataset:
#     1) Results_by_ind.csv  -> per-individual total distance travelled
#        (Traveled_Dist), with identity parsed from the Individual column
#     2) net_distance_ALL.csv -> per-individual net displacement (mm),
#        generated by 01_calc_net_distance.R
#     3) movement_row_clean.csv -> per-arena infection metadata (intensity,
#        byssus threads, shell length, etc.)
#   Individual-level total and net distances are merged and used to
#   calculate a confinement index (net displacement / total distance) per
#   individual, then averaged to arena level. Infection metadata are merged
#   in to produce arena-level summary infection intensity.
#   Output: arena_model.csv, the arena-level dataset used as input for
#   02_merge_aggregation_movement.R
# =============================================================================

library(dplyr)
library(tidyr)
library(stringr)

# 1. Load individual-level total distance data

total <- read.csv(
  "data/raw/Results_by_ind.csv",
  header = TRUE,
  sep = ";",
  stringsAsFactors = FALSE,
  fileEncoding = "UTF-8"
)

head(total)
View(total)

# Parse individual identity from the Individual column (e.g. "1_CM_3")
total2 <- total %>%
  separate(
    Individual,
    into = c("Rep", "Group", "ID"),
    sep = "_",
    remove = FALSE
  )

View(total2)
head(total2)

# 2. Load individual-level net displacement data

total3 <- read.csv(
  "data/processed/net_distance_ALL.csv",
  header = TRUE,
  sep = ",",
  stringsAsFactors = FALSE,
  fileEncoding = "UTF-8"
)

head(total3)

# 3. Merge total distance and net displacement, calculate confinement index

total2$ID <- as.numeric(total2$ID)

final_all <- left_join(
  total3,
  total2,
  by = c("Rep", "Group", "ID")
)

# Confinement index: ratio of net displacement to total distance
# (0 = tortuous/local movement; 1 = straight, directed movement)
final_all$distance_ratio <- final_all$NetDistance_mm / (final_all$Traveled_Dist * 10)

head(final_all)
View(final_all)
boxplot(final_all$distance_ratio)

# 4. Summarise movement metrics to arena level

summary_arena <- final_all %>%
  group_by(Rep, Group) %>%
  summarise(
    mean_net_distance_mm   = mean(NetDistance_mm, na.rm = TRUE),
    mean_gross_distance_mm = mean(Traveled_Dist * 10, na.rm = TRUE),
    mean_CI                = mean(distance_ratio, na.rm = TRUE),
    sd_CI                  = sd(distance_ratio, na.rm = TRUE),
    n                       = n(),
    .groups = "drop"
  )

summary_arena <- summary_arena %>%
  # Remove the letter "A" from replicate IDs (e.g. "1A" -> 1) and convert to numeric
  mutate(Rep = as.numeric(gsub("A", "", Rep))) %>%
  # Rename Group column to ArenaID to better reflect arena identity
  rename(ArenaID = Group) %>%
  # Shorten distance-related variable names while keeping units explicit
  rename(
    mean_net_mm   = mean_net_distance_mm,
    mean_gross_mm = mean_gross_distance_mm
  )

View(summary_arena)
head(summary_arena)

# 5. Merge with arena-level infection metadata

movement_row <- read.csv(
  "data/raw/movement_row_clean.csv",
  header = TRUE,
  sep = ";",
  stringsAsFactors = FALSE,
  fileEncoding = "UTF-8"
)

head(movement_row)
View(movement_row)

movement_row$Rep     <- as.numeric(movement_row$Rep)
movement_row$ArenaID <- as.character(movement_row$ArenaID)
summary_arena$ArenaID <- as.character(summary_arena$ArenaID)

movement_all <- left_join(
  summary_arena,
  movement_row,
  by = c("Rep", "ArenaID")
)

# Calculate arena-level infection summary metrics
movement_all <- movement_all %>%
  group_by(Rep, ArenaID) %>%
  mutate(
    sum_intensity = sum(Intensity, na.rm = TRUE),
    n_infected    = sum(Intensity > 0, na.rm = TRUE)
  ) %>%
  ungroup()

View(movement_all)

# Save intermediate merged table
write.csv(
  movement_all,
  "data/processed/movement_all.csv",
  row.names = FALSE,
  fileEncoding = "UTF-8"
)

colnames(movement_all)
table(summary_arena$n)

# 6. Collapse to one row per arena and remove individual-level columns

arena_model <- movement_all %>%
  distinct(Rep, ArenaID, .keep_all = TRUE) %>%
  select(-Mussel_ID, -Cluster_Score, -Byssus_Threads, -Byssus_Threads.1,
         -Length.mm., -Intensity)

View(arena_model)
head(arena_model)

# 7. Export final arena-level dataset

write.csv(
  arena_model,
  "data/processed/arena_model.csv",
  row.names = FALSE,
  fileEncoding = "UTF-8"
)
