# =============================================================================
# Merge Aggregation and Movement Data
# Project: Effects of parasitic infection on predation risk responses in
#          blue mussels (Mytilus edulis)
# Description:
#   This script merges two arena-level data sources to build the final
#   dataset used for statistical analysis of aggregation and movement
#   behaviour:
#     1) Michaelis-Menten.csv -> aggregation proportion (%) recorded at
#        5-min intervals per arena (i.e. the proportion of mussels in
#        direct physical contact with at least one other mussel, out of
#        n = 7 per arena), used here to derive:
#          - Amax:           maximum aggregation proportion (%) recorded
#                             across all 5-min intervals
#          - mean_A:         arithmetic mean of the aggregation proportions
#                             across all 5-min intervals
#          - total_time_agg: cumulative duration (min) with non-zero
#                             aggregation proportion, calculated as the
#                             number of 5-min intervals with aggregation
#                             > 0, multiplied by 5
#     2) arena_model.csv -> arena-level movement and infection metrics
#        (mean net/gross distance, confinement index, byssus thread count,
#        infection intensity), generated by 02_build_arena_model.R
#   Output: merged_movement.csv, the arena-level dataset used as input for
#   the aggregation and movement statistical models
# =============================================================================

library(dplyr)

# 1. Read data

total <- read.csv(
  "data/raw/Michaelis-Menten.csv",
  header = TRUE,
  sep = ";",
  stringsAsFactors = FALSE,
  fileEncoding = "UTF-8"
)

View(total)

move_total <- read.csv(
  "data/processed/arena_model.csv",
  header = TRUE,
  sep = ",",
  stringsAsFactors = FALSE,
  fileEncoding = "UTF-8"
)

View(move_total)

# 2. Clean data

total <- total %>%
  mutate(
    ArenaID = trimws(Arena.ID),   # clean spaces
    Group   = trimws(Group),
    Rep     = as.numeric(Rep),
    
    # convert "57,14%" -> 57.14
    A_numeric = as.numeric(gsub("%", "", gsub(",", ".", A.t.)))
  )

move_total <- move_total %>%
  mutate(
    ArenaID = trimws(ArenaID),
    Group   = trimws(Group),
    Rep     = as.numeric(Rep)
  )

# 3. Calculate aggregation metrics

summary_df <- total %>%
  group_by(ArenaID, Rep, Group) %>%
  summarise(
    Start_Time     = first(Start_Time..min.),
    Amax           = max(A_numeric, na.rm = TRUE),
    mean_A         = mean(A_numeric, na.rm = TRUE),
    total_time_agg = sum(A_numeric > 0) * 5,  # minutes
    .groups = "drop"
  )

# 4. Merge datasets
# IMPORTANT: remove duplicate Group column from move_total

move_total_clean <- move_total %>%
  select(-Group)

merged_movement <- summary_df %>%
  left_join(move_total_clean, by = c("ArenaID", "Rep"))

# 5. Diagnostics (VERY IMPORTANT)

# Check column names
print(colnames(merged_movement))

# Check structure
str(merged_movement)

# Check missing matches
missing_check <- merged_movement %>%
  filter(if_any(everything(), is.na))
View(missing_check)

# Check duplicates (should be zero)
duplicates <- merged_movement %>%
  count(ArenaID, Rep) %>%
  filter(n > 1)
View(duplicates)

colSums(is.na(merged_movement))

merged_movement <- merged_movement %>%
  mutate(Start_Time = Start_Time.x) %>%
  select(-Start_Time.x, -Start_Time.y)

colnames(merged_movement)

# Final clean table
View(merged_movement)

# 6. Remove unwanted columns

merged_movement <- merged_movement %>%
  select(-P_Status, -Notes)

View(merged_movement)

# Export results

write.csv(
  merged_movement,
  "data/processed/merged_movement.csv",
  row.names = FALSE
)
